// <auto-generated />
using System;
using DnDBot.Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDBot.Bot.Migrations
{
    [DbContext(typeof(DnDBotDbContext))]
    [Migration("20250708023912_Inicial_00")]
    partial class Inicial_00
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("AntecedentePericia", b =>
                {
                    b.Property<string>("AntecedentesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PericiasId")
                        .HasColumnType("TEXT");

                    b.HasKey("AntecedentesId", "PericiasId");

                    b.HasIndex("PericiasId");

                    b.ToTable("AntecedentePericia");
                });

            modelBuilder.Entity("Classe_Pericia", b =>
                {
                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PericiaId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClasseId", "PericiaId");

                    b.HasIndex("PericiaId");

                    b.ToTable("Classe_Pericia", (string)null);
                });

            modelBuilder.Entity("DnDBot.Bot.Models.AntecedenteModels.Antecedente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdiomasAdicionais")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requisitos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Antecedente");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.AntecedenteModels.Defeito", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AntecedenteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AntecedenteId");

                    b.ToTable("Defeito");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.AntecedenteModels.Ideal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AntecedenteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AntecedenteId");

                    b.ToTable("Ideal");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.AntecedenteModels.Vinculo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AntecedenteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AntecedenteId");

                    b.ToTable("Vinculo");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Alinhamento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alinhamento");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.AlinhamentoTag", b =>
                {
                    b.Property<string>("AlinhamentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("AlinhamentoId", "Tag");

                    b.ToTable("AlinhamentoTag");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.AntecedenteTag", b =>
                {
                    b.Property<string>("AntecedenteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("AntecedenteId", "Tag");

                    b.ToTable("AntecedenteTag");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ArmaRequisitoAtributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArmaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Atributo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArmaId");

                    b.ToTable("ArmaRequisitoAtributo");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ArmaTag", b =>
                {
                    b.Property<string>("ArmaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("ArmaId", "Tag");

                    b.ToTable("ArmaTag");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ArmaduraTag", b =>
                {
                    b.Property<string>("ArmaduraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("ArmaduraId", "Tag");

                    b.ToTable("ArmaduraTag");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseMagia", b =>
                {
                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MagiaId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClasseId", "MagiaId");

                    b.HasIndex("MagiaId");

                    b.ToTable("ClasseMagias");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClassePericia", b =>
                {
                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PericiaId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClasseId", "PericiaId");

                    b.HasIndex("PericiaId");

                    b.ToTable("ClassePericias");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseProficienciaArma", b =>
                {
                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmaId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClasseId", "ArmaId");

                    b.HasIndex("ArmaId");

                    b.ToTable("ClasseProficienciasArmas");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseProficienciaArmadura", b =>
                {
                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmaduraId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClasseId", "ArmaduraId");

                    b.HasIndex("ArmaduraId");

                    b.ToTable("ClasseProficienciasArmaduras");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseProficienciaMulticlasse", b =>
                {
                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdProficiencia")
                        .HasColumnType("TEXT");

                    b.HasKey("ClasseId", "IdProficiencia");

                    b.ToTable("ClasseProficienciasMulticlasse");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseSalvaguarda", b =>
                {
                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdSalvaguarda")
                        .HasColumnType("TEXT");

                    b.HasKey("ClasseId", "IdSalvaguarda");

                    b.ToTable("ClasseSalvaguardas");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseTag", b =>
                {
                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("ClasseId", "Tag");

                    b.ToTable("ClasseTag");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.FerramentaTag", b =>
                {
                    b.Property<string>("FerramentaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("FerramentaId", "Tag");

                    b.ToTable("FerramentaTag");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.FichaPersonagemTag", b =>
                {
                    b.Property<Guid>("FichaPersonagemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("FichaPersonagemId", "Tag");

                    b.ToTable("FichaPersonagemTag");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.MagiaTag", b =>
                {
                    b.Property<string>("MagiaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("MagiaId", "Tag");

                    b.ToTable("MagiaTag");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.RacaTag", b =>
                {
                    b.Property<string>("RacaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("RacaId", "Tag");

                    b.ToTable("RacaTag");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.SubRacaAlinhamento", b =>
                {
                    b.Property<string>("SubRacaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlinhamentoId")
                        .HasColumnType("TEXT");

                    b.HasKey("SubRacaId", "AlinhamentoId");

                    b.HasIndex("AlinhamentoId");

                    b.ToTable("SubRacaAlinhamento");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.SubRacaTag", b =>
                {
                    b.Property<string>("SubRacaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("SubRacaId", "Tag");

                    b.ToTable("SubRacaTag");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.BonusAtributo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Atributo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FichaPersonagemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubRacaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FichaPersonagemId");

                    b.HasIndex("SubRacaId");

                    b.ToTable("BonusAtributos", (string)null);
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Caracteristica", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AcaoRequerida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Alvo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AntecedenteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CondicaoAtivacao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DuracaoEmRodadas")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FichaPersonagemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NivelMaximo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelMinimo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrigemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsosPorDescansoCurto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsosPorDescansoLongo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AntecedenteId");

                    b.HasIndex("FichaPersonagemId");

                    b.ToTable("Caracteristica");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.CaracteristicaPorNivel", b =>
                {
                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaracteristicaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClasseId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubclasseId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClasseId", "Nivel", "CaracteristicaId");

                    b.HasIndex("CaracteristicaId");

                    b.HasIndex("ClasseId1");

                    b.HasIndex("SubclasseId");

                    b.ToTable("CaracteristicaPorNivel");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Classe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadoVida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdHabilidadeConjuracao")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("IdItensIniciais")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("IdSalvaguardas")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("PapelTatico")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubclassePorNivel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsaMagiaPreparada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classe");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.DificuldadePericia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PericiaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PericiaId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PericiaId");

                    b.HasIndex("PericiaId1");

                    b.ToTable("DificuldadePericia");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.EspacoMagiaPorNivel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoMagia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.ToTable("EspacoMagiaPorNivel");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.FichaPersonagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlinhamentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AntecedenteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Carisma")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Constituicao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Deslocamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Destreza")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Forca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("JogadorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RacaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sabedoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubracaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tamanho")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VisaoNoEscuro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FichaPersonagem");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Idioma", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AntecedenteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AntecedenteId");

                    b.ToTable("Idioma", (string)null);
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Magia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alcance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alvo")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaEfeito")
                        .HasColumnType("TEXT");

                    b.Property<string>("AtributoTesteResistencia")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ClassesPermitidas")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ComponenteMaterial")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ComponenteMaterialConsumido")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ComponenteSomatico")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ComponenteVerbal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concentração")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("CondicoesAplicadas")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("CondicoesRemovidas")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustoComponenteMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadoDano")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetalhesMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EfeitoPorTurno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Escalonamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Escola")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FichaPersonagemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FocoNecessario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LimiteUso")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MetadeNoTeste")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroDeUsos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumeroMaximoAlvos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PodeSerRitual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recarga")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequerLinhaDeVisao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequerLinhaReta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TempoConjuracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDano")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaPersonagemId");

                    b.ToTable("Magia");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Proficiencia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FichaPersonagemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaPersonagemId");

                    b.ToTable("Proficiencia");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.QuantidadePorNivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClasseId1")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("ClasseId1");

                    b.ToTable("QuantidadePorNivel");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Raca", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Raca");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.RequisitoMulticlasse", b =>
                {
                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Atributo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClasseId", "Atributo");

                    b.ToTable("RequisitoMulticlasse");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Resistencia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FichaPersonagemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaPersonagemId");

                    b.ToTable("Resistencia");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.SubRaca", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Deslocamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("RacaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tamanho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisaoNoEscuro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RacaId");

                    b.ToTable("SubRaca");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Subclasse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClasseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.ToTable("Subclasse");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.EquipamentoItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemInventarioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.HasIndex("ItemInventarioId");

                    b.ToTable("EquipamentoItem");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Inventario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaPersonagemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<double>("PesoMaximo")
                        .HasColumnType("REAL");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaPersonagemId")
                        .IsUnique();

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AnatomiasPermitidas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Empilhavel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Equipavel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<double>("PesoUnitario")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("RacasPermitidas")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValorCobre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasDiscriminator().HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.ItemInventario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AntecedenteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemBaseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Versao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AntecedenteId");

                    b.HasIndex("InventarioId");

                    b.HasIndex("ItemBaseId");

                    b.ToTable("ItemInventario");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.OpcaoEscolha<DnDBot.Bot.Models.Ficha.Idioma>", b =>
                {
                    b.Property<int>("QuantidadeEscolhas")
                        .HasColumnType("INTEGER");

                    b.ToTable("OpcaoEscolha<Idioma>");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.OpcaoEscolha<DnDBot.Bot.Models.Pericia>", b =>
                {
                    b.Property<int>("QuantidadeEscolhas")
                        .HasColumnType("INTEGER");

                    b.ToTable("OpcaoEscolha<Pericia>");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Pericia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AtributoBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtributosAlternativos")
                        .HasColumnType("TEXT");

                    b.Property<int>("BonusAdicional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusBase")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhProficiente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fonte")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagina")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TemEspecializacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pericia");
                });

            modelBuilder.Entity("FerramentaPericia", b =>
                {
                    b.Property<string>("FerramentaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PericiaId")
                        .HasColumnType("TEXT");

                    b.HasKey("FerramentaId", "PericiaId");

                    b.HasIndex("PericiaId");

                    b.ToTable("FerramentaPericia");
                });

            modelBuilder.Entity("FichaPersonagem_Idiomas", b =>
                {
                    b.Property<Guid>("FichaPersonagemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdiomaId")
                        .HasColumnType("TEXT");

                    b.HasKey("FichaPersonagemId", "IdiomaId");

                    b.HasIndex("IdiomaId");

                    b.ToTable("FichaPersonagem_Idiomas", (string)null);
                });

            modelBuilder.Entity("SubRaca_Caracteristicas", b =>
                {
                    b.Property<string>("CaracteristicaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubRacaId")
                        .HasColumnType("TEXT");

                    b.HasKey("CaracteristicaId", "SubRacaId");

                    b.HasIndex("SubRacaId");

                    b.ToTable("SubRaca_Caracteristicas");
                });

            modelBuilder.Entity("SubRaca_Idioma", b =>
                {
                    b.Property<string>("IdiomaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubRacaId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdiomaId", "SubRacaId");

                    b.HasIndex("SubRacaId");

                    b.ToTable("SubRaca_Idioma");
                });

            modelBuilder.Entity("SubRaca_MagiasRaciais", b =>
                {
                    b.Property<string>("MagiaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubRacaId")
                        .HasColumnType("TEXT");

                    b.HasKey("MagiaId", "SubRacaId");

                    b.HasIndex("SubRacaId");

                    b.ToTable("SubRaca_MagiasRaciais");
                });

            modelBuilder.Entity("SubRaca_Proficiencias", b =>
                {
                    b.Property<string>("ProficienciaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubRacaId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProficienciaId", "SubRacaId");

                    b.HasIndex("SubRacaId");

                    b.ToTable("SubRaca_Proficiencias");
                });

            modelBuilder.Entity("SubRaca_Resistencias", b =>
                {
                    b.Property<string>("ResistenciaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubRacaId")
                        .HasColumnType("TEXT");

                    b.HasKey("ResistenciaId", "SubRacaId");

                    b.HasIndex("SubRacaId");

                    b.ToTable("SubRaca_Resistencias");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Arma", b =>
                {
                    b.HasBaseType("DnDBot.Bot.Models.ItensInventario.Item");

                    b.Property<int?>("Alcance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlcanceArremesso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaAtaque")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AtaquesEspeciais")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("BonusContraTipos")
                        .HasColumnType("TEXT");

                    b.Property<int>("BonusMagico")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CustoReparo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadoDano")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadoDanoVersatil")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurabilidadeAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurabilidadeMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EMagica")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EhDuasMaos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EhLeve")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EhVersatil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fabricante")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MagiasAssociadas")
                        .HasColumnType("TEXT");

                    b.Property<int>("MunicaoPorAtaque")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeSerArremessada")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("PropriedadesEspeciais")
                        .HasColumnType("TEXT");

                    b.Property<string>("Raridade")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegraCritico")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequerRecarga")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Requisitos")
                        .HasColumnType("TEXT");

                    b.Property<int>("TempoRecargaTurnos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoAcao")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDano")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TipoDanoSecundario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoMunicao")
                        .HasColumnType("TEXT");

                    b.ToTable("Item", t =>
                        {
                            t.Property("BonusMagico")
                                .HasColumnName("Arma_BonusMagico");

                            t.Property("DurabilidadeAtual")
                                .HasColumnName("Arma_DurabilidadeAtual");

                            t.Property("DurabilidadeMaxima")
                                .HasColumnName("Arma_DurabilidadeMaxima");

                            t.Property("EMagica")
                                .HasColumnName("Arma_EMagica");

                            t.Property("Fabricante")
                                .HasColumnName("Arma_Fabricante");

                            t.Property("PropriedadesEspeciais")
                                .HasColumnName("Arma_PropriedadesEspeciais");

                            t.Property("Raridade")
                                .HasColumnName("Arma_Raridade");

                            t.Property("Tipo")
                                .HasColumnName("Arma_Tipo");
                        });

                    b.HasDiscriminator().HasValue("Arma");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Armadura", b =>
                {
                    b.HasBaseType("DnDBot.Bot.Models.ItensInventario.Item");

                    b.Property<int>("BonusMagico")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseArmadura")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Custo")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurabilidadeAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurabilidadeMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EMagica")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fabricante")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ImunidadesDano")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<int>("PenalidadeFurtividade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PermiteFurtividade")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("PropriedadesEspeciais")
                        .HasColumnType("TEXT");

                    b.Property<string>("Raridade")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequisitoForca")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ResistenciasDano")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Armadura");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Ferramenta", b =>
                {
                    b.HasBaseType("DnDBot.Bot.Models.ItensInventario.Item");

                    b.Property<string>("AntecedenteId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequerProficiencia")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AntecedenteId");

                    b.HasDiscriminator().HasValue("Ferramenta");
                });

            modelBuilder.Entity("AntecedentePericia", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.AntecedenteModels.Antecedente", null)
                        .WithMany()
                        .HasForeignKey("AntecedentesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Pericia", null)
                        .WithMany()
                        .HasForeignKey("PericiasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Classe_Pericia", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", null)
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Classe_Pericia_Classe");

                    b.HasOne("DnDBot.Bot.Models.Pericia", null)
                        .WithMany()
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Classe_Pericia_Pericia");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.AntecedenteModels.Antecedente", b =>
                {
                    b.OwnsMany("DnDBot.Bot.Models.ItensInventario.Moeda", "RiquezaInicial", b1 =>
                        {
                            b1.Property<string>("Tipo")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AntecedenteId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Tipo");

                            b1.HasIndex("AntecedenteId");

                            b1.ToTable("Antecedente_RiquezaInicial", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AntecedenteId");
                        });

                    b.Navigation("RiquezaInicial");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.AntecedenteModels.Defeito", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.AntecedenteModels.Antecedente", null)
                        .WithMany("Defeitos")
                        .HasForeignKey("AntecedenteId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.AntecedenteModels.Ideal", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.AntecedenteModels.Antecedente", null)
                        .WithMany("Ideais")
                        .HasForeignKey("AntecedenteId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.AntecedenteModels.Vinculo", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.AntecedenteModels.Antecedente", null)
                        .WithMany("Vinculos")
                        .HasForeignKey("AntecedenteId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.AlinhamentoTag", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Alinhamento", "Alinhamento")
                        .WithMany("AlinhamentoTags")
                        .HasForeignKey("AlinhamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alinhamento");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.AntecedenteTag", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.AntecedenteModels.Antecedente", "Antecedente")
                        .WithMany("AntecedenteTags")
                        .HasForeignKey("AntecedenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antecedente");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ArmaRequisitoAtributo", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.ItensInventario.Arma", "Arma")
                        .WithMany("RequisitosAtributos")
                        .HasForeignKey("ArmaId");

                    b.Navigation("Arma");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ArmaTag", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.ItensInventario.Arma", "Arma")
                        .WithMany("ArmaTags")
                        .HasForeignKey("ArmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arma");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ArmaduraTag", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.ItensInventario.Armadura", "Armadura")
                        .WithMany("ArmaduraTags")
                        .HasForeignKey("ArmaduraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armadura");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseMagia", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.Magia", "Magia")
                        .WithMany()
                        .HasForeignKey("MagiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Magia");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClassePericia", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Pericia", "Pericia")
                        .WithMany()
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Pericia");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseProficienciaArma", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.ItensInventario.Arma", "Arma")
                        .WithMany()
                        .HasForeignKey("ArmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arma");

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseProficienciaArmadura", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.ItensInventario.Armadura", "Armadura")
                        .WithMany()
                        .HasForeignKey("ArmaduraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armadura");

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseProficienciaMulticlasse", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseSalvaguarda", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.ClasseTag", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany("ClasseTags")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.FerramentaTag", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.ItensInventario.Ferramenta", "Ferramenta")
                        .WithMany("FerramentaTags")
                        .HasForeignKey("FerramentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ferramenta");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.FichaPersonagemTag", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.FichaPersonagem", "FichaPersonagem")
                        .WithMany("FichaPersonagemTags")
                        .HasForeignKey("FichaPersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaPersonagem");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.MagiaTag", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Magia", "Magia")
                        .WithMany("MagiaTags")
                        .HasForeignKey("MagiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magia");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.RacaTag", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Raca", "Raca")
                        .WithMany("RacaTags")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.SubRacaAlinhamento", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Alinhamento", "Alinhamento")
                        .WithMany()
                        .HasForeignKey("AlinhamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.SubRaca", "SubRaca")
                        .WithMany("AlinhamentosComuns")
                        .HasForeignKey("SubRacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alinhamento");

                    b.Navigation("SubRaca");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Auxiliares.SubRacaTag", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.SubRaca", "SubRaca")
                        .WithMany("SubRacaTags")
                        .HasForeignKey("SubRacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubRaca");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.BonusAtributo", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.FichaPersonagem", null)
                        .WithMany("BonusAtributos")
                        .HasForeignKey("FichaPersonagemId");

                    b.HasOne("DnDBot.Bot.Models.Ficha.SubRaca", null)
                        .WithMany("BonusAtributos")
                        .HasForeignKey("SubRacaId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Caracteristica", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.AntecedenteModels.Antecedente", null)
                        .WithMany("Caracteristica")
                        .HasForeignKey("AntecedenteId");

                    b.HasOne("DnDBot.Bot.Models.Ficha.FichaPersonagem", null)
                        .WithMany("Caracteristicas")
                        .HasForeignKey("FichaPersonagemId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.CaracteristicaPorNivel", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Caracteristica", "Caracteristica")
                        .WithMany()
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", null)
                        .WithMany("CaracteristicasPorNivelList")
                        .HasForeignKey("ClasseId1");

                    b.HasOne("DnDBot.Bot.Models.Ficha.Subclasse", null)
                        .WithMany("CaracteristicasPorNivelList")
                        .HasForeignKey("SubclasseId");

                    b.Navigation("Caracteristica");

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Classe", b =>
                {
                    b.OwnsMany("DnDBot.Bot.Models.ItensInventario.Moeda", "RiquezaInicial", b1 =>
                        {
                            b1.Property<string>("Tipo")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ClasseId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Tipo");

                            b1.HasIndex("ClasseId");

                            b1.ToTable("Classe_RiquezaInicial", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClasseId");
                        });

                    b.Navigation("RiquezaInicial");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.DificuldadePericia", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Pericia", null)
                        .WithMany("Dificuldades")
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDBot.Bot.Models.Pericia", "Pericia")
                        .WithMany()
                        .HasForeignKey("PericiaId1");

                    b.Navigation("Pericia");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.EspacoMagiaPorNivel", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany("EspacosMagia")
                        .HasForeignKey("ClasseId");

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.FichaPersonagem", b =>
                {
                    b.OwnsOne("DnDBot.Bot.Models.ItensInventario.BolsaDeMoedas", "BolsaDeMoedas", b1 =>
                        {
                            b1.Property<Guid>("FichaPersonagemId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.HasKey("FichaPersonagemId");

                            b1.ToTable("BolsasDeMoedas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FichaPersonagemId");

                            b1.OwnsMany("DnDBot.Bot.Models.ItensInventario.Moeda", "Moedas", b2 =>
                                {
                                    b2.Property<Guid>("FichaPersonagemId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Tipo")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Id")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Quantidade")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("FichaPersonagemId", "Tipo");

                                    b2.ToTable("Moedas", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("FichaPersonagemId");
                                });

                            b1.Navigation("Moedas");
                        });

                    b.Navigation("BolsaDeMoedas");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Idioma", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.AntecedenteModels.Antecedente", null)
                        .WithMany("Idiomas")
                        .HasForeignKey("AntecedenteId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Magia", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.FichaPersonagem", null)
                        .WithMany("MagiasRaciais")
                        .HasForeignKey("FichaPersonagemId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Proficiencia", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.FichaPersonagem", null)
                        .WithMany("Proficiencias")
                        .HasForeignKey("FichaPersonagemId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.QuantidadePorNivel", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany("TruquesConhecidosPorNivelList")
                        .HasForeignKey("ClasseId");

                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", null)
                        .WithMany("MagiasConhecidasPorNivelList")
                        .HasForeignKey("ClasseId1");

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.RequisitoMulticlasse", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", "Classe")
                        .WithMany("RequisitosParaMulticlasseEntities")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Resistencia", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.FichaPersonagem", null)
                        .WithMany("Resistencias")
                        .HasForeignKey("FichaPersonagemId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.SubRaca", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Raca", "Raca")
                        .WithMany("SubRaca")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Subclasse", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Classe", null)
                        .WithMany("Subclasses")
                        .HasForeignKey("ClasseId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.EquipamentoItem", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.ItensInventario.Inventario", "Inventario")
                        .WithMany("Equipados")
                        .HasForeignKey("InventarioId");

                    b.HasOne("DnDBot.Bot.Models.ItensInventario.ItemInventario", "ItemInventario")
                        .WithMany()
                        .HasForeignKey("ItemInventarioId");

                    b.Navigation("Inventario");

                    b.Navigation("ItemInventario");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Inventario", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.FichaPersonagem", "FichaPersonagem")
                        .WithOne("Inventario")
                        .HasForeignKey("DnDBot.Bot.Models.ItensInventario.Inventario", "FichaPersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaPersonagem");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.ItemInventario", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.AntecedenteModels.Antecedente", null)
                        .WithMany("EquipamentosDetalhados")
                        .HasForeignKey("AntecedenteId");

                    b.HasOne("DnDBot.Bot.Models.ItensInventario.Inventario", null)
                        .WithMany("Itens")
                        .HasForeignKey("InventarioId");

                    b.HasOne("DnDBot.Bot.Models.ItensInventario.Item", "ItemBase")
                        .WithMany()
                        .HasForeignKey("ItemBaseId");

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("FerramentaPericia", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.ItensInventario.Ferramenta", null)
                        .WithMany()
                        .HasForeignKey("FerramentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Pericia", null)
                        .WithMany()
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FichaPersonagem_Idiomas", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.FichaPersonagem", null)
                        .WithMany()
                        .HasForeignKey("FichaPersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.Idioma", null)
                        .WithMany()
                        .HasForeignKey("IdiomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubRaca_Caracteristicas", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Caracteristica", null)
                        .WithMany()
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.SubRaca", null)
                        .WithMany()
                        .HasForeignKey("SubRacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubRaca_Idioma", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Idioma", null)
                        .WithMany()
                        .HasForeignKey("IdiomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.SubRaca", null)
                        .WithMany()
                        .HasForeignKey("SubRacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubRaca_MagiasRaciais", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Magia", null)
                        .WithMany()
                        .HasForeignKey("MagiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.SubRaca", null)
                        .WithMany()
                        .HasForeignKey("SubRacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubRaca_Proficiencias", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Proficiencia", null)
                        .WithMany()
                        .HasForeignKey("ProficienciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.SubRaca", null)
                        .WithMany()
                        .HasForeignKey("SubRacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubRaca_Resistencias", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.Ficha.Resistencia", null)
                        .WithMany()
                        .HasForeignKey("ResistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDBot.Bot.Models.Ficha.SubRaca", null)
                        .WithMany()
                        .HasForeignKey("SubRacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Ferramenta", b =>
                {
                    b.HasOne("DnDBot.Bot.Models.AntecedenteModels.Antecedente", null)
                        .WithMany("Ferramentas")
                        .HasForeignKey("AntecedenteId");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.AntecedenteModels.Antecedente", b =>
                {
                    b.Navigation("AntecedenteTags");

                    b.Navigation("Caracteristica");

                    b.Navigation("Defeitos");

                    b.Navigation("EquipamentosDetalhados");

                    b.Navigation("Ferramentas");

                    b.Navigation("Ideais");

                    b.Navigation("Idiomas");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Alinhamento", b =>
                {
                    b.Navigation("AlinhamentoTags");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Classe", b =>
                {
                    b.Navigation("CaracteristicasPorNivelList");

                    b.Navigation("ClasseTags");

                    b.Navigation("EspacosMagia");

                    b.Navigation("MagiasConhecidasPorNivelList");

                    b.Navigation("RequisitosParaMulticlasseEntities");

                    b.Navigation("Subclasses");

                    b.Navigation("TruquesConhecidosPorNivelList");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.FichaPersonagem", b =>
                {
                    b.Navigation("BonusAtributos");

                    b.Navigation("Caracteristicas");

                    b.Navigation("FichaPersonagemTags");

                    b.Navigation("Inventario");

                    b.Navigation("MagiasRaciais");

                    b.Navigation("Proficiencias");

                    b.Navigation("Resistencias");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Magia", b =>
                {
                    b.Navigation("MagiaTags");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Raca", b =>
                {
                    b.Navigation("RacaTags");

                    b.Navigation("SubRaca");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.SubRaca", b =>
                {
                    b.Navigation("AlinhamentosComuns");

                    b.Navigation("BonusAtributos");

                    b.Navigation("SubRacaTags");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Ficha.Subclasse", b =>
                {
                    b.Navigation("CaracteristicasPorNivelList");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Inventario", b =>
                {
                    b.Navigation("Equipados");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.Pericia", b =>
                {
                    b.Navigation("Dificuldades");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Arma", b =>
                {
                    b.Navigation("ArmaTags");

                    b.Navigation("RequisitosAtributos");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Armadura", b =>
                {
                    b.Navigation("ArmaduraTags");
                });

            modelBuilder.Entity("DnDBot.Bot.Models.ItensInventario.Ferramenta", b =>
                {
                    b.Navigation("FerramentaTags");
                });
#pragma warning restore 612, 618
        }
    }
}
